// YouTube help sections data — keybind reference for the help window

export function getYouTubeHelpSections() {
  return [
    {
      name: 'Home Page',
      keybinds: [
        { keys: ['j', '\u2193'], description: 'Navigate down' },
        { keys: ['k', '\u2191'], description: 'Navigate up' },
        { keys: ['h'], description: 'Navigate left' },
        { keys: ['l'], description: 'Navigate right' },
        { keys: ['gg'], description: 'Go to top' },
        { keys: ['G'], description: 'Go to bottom' },
        { keys: ['Enter'], description: 'Open video' },
        { keys: ['Shift+Enter'], description: 'Open in new tab' },
        { keys: ['dd'], description: 'Dismiss video' },
        { keys: ['mw'], description: 'Add to watch later' },
        { keys: ['u'], description: 'Undo watch later removal' },
        { keys: ['gh'], description: 'Go to home' },
        { keys: ['gs'], description: 'Go to subscriptions' },
        { keys: ['gy'], description: 'Go to history' },
        { keys: ['gl'], description: 'Go to library' },
        { keys: ['gw'], description: 'Go to watch later' },
        { keys: ['i'], description: 'Open search' },
        { keys: ['/'], description: 'Open local filter' },
        { keys: [':'], description: 'Open command palette' },
        { keys: [':sort da'], description: 'Sort by date' },
        { keys: [':sort du'], description: 'Sort by duration' },
        { keys: [':sort t'], description: 'Sort by title' },
        { keys: [':sort c'], description: 'Sort by channel' },
        { keys: [':sort v'], description: 'Sort by views' },
        { keys: [':sort'], description: 'Reset sort' },
      ],
    },
    {
      name: 'Watch Page',
      keybinds: [
        { keys: ['f'], description: 'Toggle fullscreen' },
        { keys: ['\u2190', '\u2192'], description: 'Skip \u00B15s' },
        { keys: ['sl'], description: 'Like video' },
        { keys: ['sd'], description: 'Dislike video' },
        { keys: ['ss'], description: 'Subscribe/unsubscribe' },
        { keys: ['sw'], description: 'Add to watch later' },
        { keys: ['gc'], description: 'Go to channel' },
        { keys: ['gh'], description: 'Go to home' },
        { keys: ['gs'], description: 'Go to subscriptions' },
        { keys: ['gy'], description: 'Go to history' },
        { keys: ['gl'], description: 'Go to library' },
        { keys: ['gw'], description: 'Go to watch later' },
        { keys: ['gg'], description: 'Go to top' },
        { keys: ['g1'], description: 'Playback speed 1x' },
        { keys: ['g2'], description: 'Playback speed 2x' },
        { keys: ['yy'], description: 'Copy video URL' },
        { keys: ['yt'], description: 'Copy video title' },
        { keys: ['Y'], description: 'Copy URL at current time' },
        { keys: ['zr'], description: 'Open recommended' },
        { keys: ['zo'], description: 'Open description' },
        { keys: ['zc'], description: 'Close description' },
        { keys: ['zp'], description: 'Open chapters' },
        { keys: ['t'], description: 'Open transcript' },
        { keys: ['['], description: 'Previous comment page' },
        { keys: [']'], description: 'Next comment page' },
        { keys: ['i'], description: 'Open search' },
        { keys: [':'], description: 'Open command palette' },
      ],
    },
    {
      name: 'Universal',
      keybinds: [
        { keys: ['Esc'], description: 'Close current overlay' },
        { keys: [':help'], description: 'Show this help window' },
        { keys: [':settings'], description: 'Open settings' },
        { keys: [':colorscheme'], description: 'Change colorscheme' },
        { keys: [':set guifont='], description: 'Change font' },
        { keys: [':q'], description: 'Exit focus mode' },
      ],
    },
  ];
}
